server:
  port: 3344
spring:
  application:
    name: cloud-config-center #注册进Eureka服务器的微服务名
  cloud:
    config:
      server:
        git:
#          uri: git@github.com:jcode95/MY-springcloud-config.git  #GitHub上面的git仓库名字
          uri: https://github.com/jcode95/MY-springcloud-config.git  #GitHub上面的git仓库名字
            # 搜索目录
          search-paths:
            - MY-springcloud-config   #这个一定要填xxx.git 的 xxx
      # 读取分支
      label: master
#rabbitmq相关配置<--------------------------
  rabbitmq:
    host: 8.136.211.134
    port: 5672
    username: guest
    password: guest

#服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka


##rabbitmq相关配置,暴露bus刷新配置的端点<--------------------------
management:
  endpoints:
    web:
      exposure:
        include: 'bus-refresh'